# Evaluating language models

This section introduces you to some basic techniques for evaluating the results of natural language processing.

After reading this section, you should:

- understand what is meant by a gold standard
- know how to evaluate agreement between human annotators
- understand simple metrics for evaluating the performance of natural language processing

## What is a gold standard?

A gold standard – also called a ground truth – refers to human-verified data that can used as a benchmark for evaluating the performance of algorithms. 

In natural language processing, a gold standard attempts to measure how well humans perform on some task.

The goal of natural language processing is to allow computers to achieve or surpass human-level performance in some pre-defined task. 

Measuring whether they can do so requires a benchmark, which is provided by the gold standard.

In reality, however, gold standards consist of *abstractions*. 

Think of placing words into word classes: word classes are not given to us by nature, but represent an abstraction that imposes structure on natural language.

Language, however, is naturally ambiguous and subjective, and the abstractions used be underdeveloped – we cannot be sure if we would describe or categorise phenomenona the same way.

This is why we need also to measure the reliability of any gold standard.

## Measuring reliability manually

This section introduces how reliability, often understood as agreement between multiple annotators, can be measured.

### Step 1: Annotate data

Sentiment analysis is a task that involves determining the sentiment of a text (for an useful overview that incorporates insights from both linguistics and natural language processing, see [Taboada](https://doi.org/10.1146/annurev-linguistics-011415-040518) (2016).

Training a sentiment analysis model requires collecting training data, that is, examples of texts associated with different sentiments.

Classify the following tweets into three categories – *positive*, *neutral* or *negative* – based on their sentiment.

Write down your decision – one per row – but **do not discuss them or show them to the person next to you.**

```
1. Updated: HSL GTFS (Helsinki, Finland) https://t.co/fWEpzmNQLz
2. current weather in Helsinki: broken clouds, -8°C 100% humidity, wind 4kmh, pressure 1061mb
3. ""suddenly became dark""? The man is confused by daylight and we let him run national infrastructure?
4. Baana bicycle counter. Today: 3 Same time last week: 1058 Trend: ↓99% This year: 819 518 Last year: 802 079 #Helsinki #pyöräily #cycling
5. What a great start for 2018! My first title at the 48th Brunswick Ballmaster Open (first… 
6. A perfect Sunday walk in the woods just a few steps from home. This is what my beloved hometown,… 
7. Went to Drug Restaurant concert today👍 It was so amazing and I think I got damn good photos with…
8. Choo Choo 🚂 train cake for little boys birthday party 🎉 - Junakakku 🚂 pikkupojan… 
9. Happy women's day ❤️💋 kisses to all you beautiful ladies out there. 😚 #awesometobeawoman
10. Good morning #Helsinki! Sun will rise in 30 minutes (local time 07:32) #Sunrise #Photo #Photography [03.10.2016]
```

Double-click this cell to edit its contents and write down your classifications below:

    1.
    2.
    3.
    4.
    5.
    6.
    7.
    8.
    9.
    10.

### Step 2: Calculate percentage agreement

When creating datasets for training models, we typically want the training data to be reliable, that is, so that we agree on whatever we are describing – in this case, the sentiment of the tweets above.

One way to measure this is simple *percentage agreement*, that is, how many times out of 10 you and the person next to you agreed on the sentiment of a tweet.

Now compare your results calculate percentage agreement by dividing the number of times you agreed by the number of items (10).

You can calculate percentage agreement by executing the cell below: just assign the number items you agree on to the variable `agreement`. 

In [ ]:
agreement = 0  # Replace this number here

agreement = agreement / 10  # Divide the count by the number of tweets

agreement

### Step 3: Calculate probabilities for each category

Percentage agreement is actually a very poor measure of agreement, as either of you may have made lucky guesses – or perhaps you considered the task boring and classified every tweet into a random category.

If you did, we have no way of knowing this, as percentage agreement cannot tell us if the result occurred by chance!

Luckily, we can estimate the possibility of *chance agreement* easily.

The first step is to count **how many times you used each available category** (positive, neutral or negative).

Assign these counts in the variables below.

In [ ]:
positive = 0
neutral = 0
negative = 0

We can convert these counts into *probabilities* by dividing them with the total number of tweets classified (10).

In [ ]:
positive = positive / 10
neutral = neutral / 10
negative = negative / 10

positive, neutral, negative

These probabilities represent the chance of *you* choosing that particular category.

Now ask the person sitting next to you for their corresponding probabilities and tell them yours as well. 

Add their probabilities to the variables below.

In [ ]:
nb_positive = 0
nb_neutral = 0
nb_negative = 0

Now that we know the probabilities for each class for both annotators, we can calculate the probability that both annotators choose the same category by chance.

This is easy: for each category, simply multiply your probability with the corresponding probability from the person next to you.

If either annotator did not assign a single tweet into a category, e.g. negative, and the other annotator did, then this effectively rules out the possibility of agreeing by chance (multiplication by zero results in zero).

In [ ]:
both_positive = positive * nb_positive
both_neutral = neutral * nb_neutral
both_negative = negative * nb_negative

### Step 4: Estimate chance agreement

Now we are ready to calculate how likely you are to agree by chance.

This is known as *expected agreement*, which is calculated by summing up your combined probabilities for each category.

In [ ]:
expected_agreement = both_positive + both_neutral + both_negative

expected_agreement

Now that we know both observed percentage agreement (`agreement`) and the agreement expected by chance (`expected_agreement`), we can use this information for a more reliable measure of *agreement*.

One such measure is [Cohen's kappa](https://en.wikipedia.org/wiki/Cohen%27s_kappa) ($\kappa$), which estimates agreement on the basis of both observed and expected agreement.

The formula for Cohen's $\kappa$ is as follows:

$\kappa = \frac{P_{observed} - P_{expected}}{1 - P_{expected}}$

As all this information is stored in our variables `agreement` and `expected_agreement`, we can easily count the $\kappa$ score using the code below.

Note that we must wrap the subtractions into parentheses to perform them before division.

In [ ]:
kappa = (agreement - expected_agreement) / (1 - expected_agreement)

kappa

This gives us the result for Cohen's $\kappa$.

Let's now consider how to interpret its value.

## Cohen's $\kappa$ as a measure of agreement

The theoretical value Cohen's $\kappa$ runs from $-1$ indicating perfect disagreement to $+1$ for perfect agreement, with $0$ standing for completely random agreement.

The $\kappa$ score is often interpreted as a measure of the strength of agreement.

[Landis and Koch](https://doi.org/10.2307/2529310) (1977) famously proposed the following benchmarks, which should nevertheless be taken with a pinch of salt as the divisions are completely arbitrary.

```
| Cohen's K | Strength of agreement|
|----------------------------------|
| <0.00     | Poor                 |
| 0.00–0.20 | Slight               |
| 0.21–0.40 | Fair                 |
| 0.41–0.60 | Moderate             |
| 0.61–0.80 | Substantial          |
| 0.81–1.00 | Almost perfect       |
|----------------------------------|
```

Cohen's $\kappa$ can be used to measure agreement between **two** annotators and the categories available must be **fixed** in advance. 

For measuring agreement between more than two annotators, one must use a measure such as [Fleiss' $\kappa$](https://en.wikipedia.org/wiki/Fleiss%27_kappa).

Cohen's $\kappa$ and many more measures of agreement are implemented in various Python libraries, so one rarely needs to perform the calculations manually.

The [*scikit-learn*](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.cohen_kappa_score.html#sklearn.metrics.cohen_kappa_score) library (`sklearn`), for instance, includes an implementation of Cohen's $\kappa$.

Let's import the `cohen_kappa_score()` function for calculating Cohen's $\kappa$ from scikit-learn.

This function takes two *lists* as input and calculates the $\kappa$ score between them.

In [2]:
from sklearn.metrics import cohen_kappa_score

We can then define two lists of part-of-speech tags, which make up our toy example for calculating Cohen's $\kappa$.

In [3]:
a1 = ['ADJ', 'AUX', 'NOUN', 'VERB', 'VERB']
a2 = ['ADJ', 'VERB', 'NOUN', 'NOUN', 'VERB']

The next step is to feed the two lists, `a1` and `a2`, to the `cohen_kappa_score()` function.

In [4]:
cohen_kappa_score(a1, a2)

0.44444444444444453

According to the benchmark from Landis and Koch, this score would indicate moderate agreement.

Generally, Cohen's $\kappa$ can be used for measuring agreement on all kinds of tasks that involve placing items into categories.

It is rarely necessary to annotate the whole dataset when measuring agreement – a random sample is often enough.

Finally, if Cohen's $\kappa$ suggests that the human annotators agree on whatever they are categorising, we can assume that the end result is *reliable*.

## Evaluating the performance of language models

Once we have a sufficiently *reliable* gold standard, we can use the gold standard to measure the performance of language models.

Let's assume that we have a reliable gold standard consisting of 10 tokens annotated for their part-of-speech tags.

These part-of-speech tags are given in the list `gold_standard`.

In [10]:
gold_standard = ['ADJ', 'ADJ', 'AUX', 'VERB', 'AUX', 'NOUN', 'NOUN', 'ADJ', 'DET', 'PRON']

We then retrieve the predictions for the same tokens from some language model and store them in a list named `predictions`.

In [11]:
predictions = ['NOUN', 'ADJ', 'AUX', 'VERB', 'AUX', 'NOUN', 'VERB', 'ADJ', 'DET', 'PROPN']

### Metrics

Now that we have two sets of annotations to compare, let's import some metrics from the *scikit-learn* library and apply them to our data.

In [12]:
from sklearn import metrics

First of all, we can calculate [**accuracy**](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score) using the `accuracy_score()` function, which is precisely the same as observed agreement.

This function takes two lists as input.

In [13]:
metrics.accuracy_score(gold_standard, predictions)

0.7

Note that accuracy suffers from the same shortcoming as observed agreement – we cannot know if the language model is simply making lucky guesses.

However, given that we are working with a toy example, we can easily verify that 7 out of 10 part-of-speech tags match. This gives an accuracy of 0.7 or 70%.

To better evaluate the performance of the language model against our gold standard, let's organise the results into a *confusion matrix*.

To do so, we need all the classes that occur in `gold_standard` and `predictions`.

We can easily get a list of unique classes using Python's `set()` function.

We then sort the set and cast it into a list.

In [14]:
pos_tags = set(gold_standard + predictions)

pos_tags = list(sorted(pos_tags))

pos_tags

['ADJ', 'AUX', 'DET', 'NOUN', 'PRON', 'PROPN', 'VERB']

We can compile this information into a table, in which the rows stand for the gold standard and the columns stand for predictions made by the language model.

This kind of table is commonly called a *confusion matrix*.

The table is populated by simply walking through each pair of items in the gold standard and model predictions, adding $+1$ to the cell for this combination.

For example, the first item in `gold_standard` is ADJ, whereas the first item in `predictions` is NOUN. 

We then find the row for ADJ and the column for NOUN and add one to this cell.

```
                            PREDICTIONS

           | ADJ | AUX | DET | NOUN | PRON | PROPN | VERB |
   |-------|-----|-----|-----|------|------|-------|------|
   | ADJ   | 2   | 0   | 0   | 1    | 0    | 0     | 0    |
G  | AUX   | 0   | 2   | 0   | 0    | 0    | 0     | 0    |
O  | DET   | 0   | 0   | 1   | 0    | 0    | 0     | 0    |
L  | NOUN  | 0   | 0   | 0   | 1    | 0    | 0     | 1    |
D  | PRON  | 0   | 0   | 0   | 0    | 0    | 1     | 0    |
   | PROPN | 0   | 0   | 0   | 0    | 0    | 0     | 0    |
   | VERB  | 0   | 0   | 0   | 0    | 0    | 0     | 1    |
   |------------------------------------------------------|
```

As you can see, the correct predictions form a roughly diagonal line across the table.

We can use the table to derive two additional metrics for each class: **precision** and **recall**.

Precision is the **proportion of correct predictions per class**. In plain words, precision tells you how many predictions were correct for each class.

For example, the sum for column VERB is $2$, of which $1$ prediction is correct (that which is located in the row VERB).

Hence precision for VERB is $1 / 2 = 0.5$ – half of the tokens predicted to be verbs were classified correctly. The same holds true for NOUN, as the column sums up two $2$, but only $1$ prediction is in the correct row.

Recall, in turn, gives the proportion of correct predictions for all examples of that class. 

Put differently, recall tells you **how many actual instances of a given class the model was able to "find"**.

For example, the sum for row ADJ is $3$: there are three adjectives in the gold standard, but only two are located in the corresponding column for ADJ.

This means that recall for ADJ is $2 / 3 = 0.66$ – approximately 66% of the adjectives present in the gold standard were classified correctly. For NOUN, recall is $1 / 2 = 0.5$.

The *scikit-learn* library provides a `confusion_matrix()` function for automatically generating confusion matrices. 

Execute the following cell and compare it to the manually created matrix above.

In [15]:
print(metrics.confusion_matrix(gold_standard, predictions))

[[2 0 0 1 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]]


To evaluate the ability of the language model to predict the correct part-of-speech tag, we can use [**precision**](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html#sklearn.metrics.precision_score), which is implemented in the `precision_score()` function in the *scikit-learn* library.

Because we have more than two classes for part-of-speech tags instead of just two (binary) classes, we must define how the results for each class are processed.

This option is set using the `average` argument of the `precision_score()` function.

If we set `average` to `None`, the function returns precision for each class.

The results are organised according to a sorted *set* of labels present in `gold_standard` and `predictions`.

In [ ]:
precision = metrics.precision_score(gold_standard, predictions, average=None)

precision

Note that *scikit-learn* will raise a *warning*, since not all classes in `predictions` are present in `gold_standard`. Note, however, that this is a warning, not an error.

The output is a [NumPy](https://www.numpy.org) array. NumPy is a powerful library for working with numerical data which can be found under the hood of many Python libraries.

If we want to combine our list of labels in `pos_tags` with the precision scores in `precision`, we can do this using Python's `zip()` function, which joins together lists and/or arrays of the same size. To view the result, we must cast it into a dictionary using `dict()`.

In [ ]:
dict(zip(pos_tags, precision))

If we want to get single precision score for all classes, we can use the option given by the string `'macro'`, which means that each class is treated as equally important regardless of how many examples of this class can be found in the data.

In [ ]:
macro_precision = metrics.precision_score(gold_standard, predictions, average='macro')

macro_precision

The macro precision is calculated by summing up the precision scores and dividing them by the number of classes.

We can easily verify this manually.

In [ ]:
sum(precision) / len(precision)

Calculating recall is equally easy using the `recall_score()` function from *scikit-learn*.

In [ ]:
recall = metrics.recall_score(gold_standard, predictions, average=None)

dict(zip(pos_tags, recall))

The *scikit-learn* library provides a very useful function for providing an overview of classification performance called `classification_report()`.

This will give you the precision and recall scores for each class, together with the [F1-score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html), which is the weighted average of precision and recall. The column for support counts the number of instances in each class.

As you can see, the micro average scores, which compare the gold standard and predictions *globally*, are the same as accuracy.

The macro average scores, in turn, correspond to those that we calculated above.

Finally, the weighted averages take into account the number of instances in each class.

In [ ]:
print(metrics.classification_report(gold_standard, predictions))

This section should have given you an idea how to assess the reliability of human annotations, and how reliable annotations can be used as a gold standard for benchmarking the performance of natural language processing.